config/routes.rb
Rails.application.routes.draw do
 
  root to: redirect('/container')

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

  namespace :admin do
    resources :lessons, param: :slug
  end

  ActiveAdmin.routes(self)

  resources :users do
    resources :completed_lessons
  end

  get 'container', to: 'container#index'
  get 'team', to: 'team#index'
  resources :lessons, param: :slug

  resources :completed_lessons do
    put "togglelesson"
  end
  
  get "completed_lessons/:id/togglelesson" => "completed_lessons#togglelesson", :as => "togglelesson", :via => [:get]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed_lesson.rb
class CompletedLesson < ApplicationRecord
	belongs_to :user
	belongs_to :lesson

	before_validation :set_default_to_completed

	private

	def set_default_to_completed
		self.completed = true if self.completed.nil?
	end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :completed_lessons
  has_many :users, through: :completed_lessons

  def to_param
    slug
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :completed_lessons
  has_many :lessons, through: :completed_lessons

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/completed_lessons_controller.rb
class CompletedLessonsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_completed_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @completed_lessons = CompletedLesson.all
  end

  def show
  end

  def new
    @completed_lesson = CompletedLesson.new
  end

  def edit
  end

  def create
    @completed_lesson = CompletedLesson.new(completed_lesson_params)
    @lessons = Lesson.all
    lessonSlug = @completed_lesson.lesson.slug
    @lesson = Lesson.find_by(slug: lessonSlug)

    @completed_lesson.user = current_user
    @completed_lesson.completed = true

    if @completed_lesson.save
      redirect_to lesson_path(slug: lessonSlug, anchor: 'mark-complete')
   else
     redirect_to @lesson, notice: 'Error: please try again later.'
   end
  end

  def update
    respond_to do |format|
      if @completed_lesson.update(completed_lesson_params)
        format.html { redirect_to @completed_lesson, notice: 'Completed lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @completed_lesson }
      else
        format.html { render :edit }
        format.json { render json: @completed_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def togglelesson
    @completed_lesson = current_user.completed_lessons.find(params[:id])
    @lessons = Lesson.all
    lessonSlug = @completed_lesson.lesson.slug
    @lesson = Lesson.find_by(slug: lessonSlug)

    if @completed_lesson.completed?
      @completed_lesson.completed  = 'false'
    else
      @completed_lesson.completed  = 'true'
    end

    @completed_lesson.save
    
    if @completed_lesson.save
      redirect_to lesson_path(slug: lessonSlug, anchor: 'mark-complete')
    else
      redirect_to @lesson, notice: 'Error: please try again later.'
    end
  end

  def destroy
    @completed_lesson.destroy
    respond_to do |format|
      format.html { redirect_to completed_lessons_url, notice: 'Completed lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_completed_lesson
      @completed_lesson = current_user.completed_lessons.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def completed_lesson_params
      params.require(:completed_lesson).permit(:lesson_id)
    end
end

app/controllers/container_controller.rb
# frozen_string_literal: true

class ContainerController < ApplicationController
  layout "application"
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def show
    @completed_lesson = @lesson.completed_lessons.build
    @completed = current_user.completed_lessons.find_by(lesson: @lesson)
  end

  def new
    @lesson = Lesson.new
  end

  def edit
  end

  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_lesson
    @lesson = Lesson.find_by(slug: params[:slug])
  end

  def lesson_params
    params.require(:lesson).permit(:name, :description, :slug)
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = Lesson.all
  end

  def show
    @completed_lessons = @users.completed_lessons.all
    @completed_lesson = @users.completed_lessons.build
  end

  def new
    @user = User.find(params[:user_id])
    @completed_lesson = @user.completed_lessons.build
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = Lesson.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :description, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_lessons_helper.rb
module CompletedLessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/completed_lessons/_form.html.erb
<%= form_with(model: @completed_lesson, local: true) do |form| %>

  <% if @completed_lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(completed_lesson.errors.count, "error") %> prohibited this completed_lesson from being saved:</h2>
      <ul>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id  %>
  <%= form.hidden_field :completed  %>
  <%= form.hidden_field :lesson_id  %>

  <div>
    <%= form.submit 'mark complete', class: 'btn mark-complete' %>
  </div>
<% end %>

app/views/completed_lessons/edit.html.erb
<h1>Editing Completed Lesson</h1>

<%= render 'form', completed_lesson: @completed_lesson %>

<%= link_to 'Show', @completed_lesson %> |
<%= link_to 'Back', completed_lessons_path %>

app/views/completed_lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Completed Lessons</h1>

  <div class="lessonContainer">
    <table class="table table-bordered">
      <tbody>
        <% @completed_lessons.each do |completed_lesson| %>
          <% if completed_lesson.completed == true &&  current_user.id == completed_lesson.user_id%>
            <tr>
            <td><%= completed_lesson.lesson&.name %></td>
            <td><%= link_to 'mark incomplete', togglelesson_path(completed_lesson), :method => :put %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

<br>

app/views/completed_lessons/new.html.erb
<h1>New Completed Lesson</h1>

<%= render 'form', completed_lesson: @completed_lesson %>

<%= link_to 'Back', completed_lessons_path %>

app/views/completed_lessons/show.html.erb
<p>
  <strong>Lesson:</strong>
  <%= @completed_lesson.lesson_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @completed_lesson.user_id %>
</p>


<%= link_to 'Edit', edit_completed_lesson_path(@completed_lesson) %> |
<%= link_to 'Back', completed_lessons_path %>

app/views/container/index.html.erb
<%= react_component("Container", props: @container_props, prerender: false) %>

app/views/hello_world/index.html.erb
<head>
	<%= stylesheet_link_tag "/css/style.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'skrollr.min.js' %>


</head>
<body>
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>
    <%= javascript_pack_tag 'application' %>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scimo</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_pack_tag 'application' %>

  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/container">ScienceMotions</a>
      </div>

      <div class="dropdown pull-right">
        <button class="btn btn-secondary dropdown-toggle ml-auto" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
      <ul>
        <li>Logged in as <strong><%= current_user.email %></strong>.</li>
        <li><%= link_to 'Completed lessons', completed_lessons_url, :class => 'navbar-link dropdown-item' %> </li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link dropdown-item' %> </li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link dropdown-item'  %></li>
      </ul>
      <% else %>
      <ul>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link dropdown-item'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link dropdown-item'  %></li>
      </ul>
      <% end %>
      </p>
     </div>
  </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/container">home</a></li>
        </ul>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/lessons">lessons</a></li>
        </ul>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/team">team</a></li>
        </ul>
      </div>

    </div>
  </nav>

  <div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>

      <footer>
      <div>
      </div>
    </footer>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'container-bundle' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/layouts/container.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'container-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :lesson_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :lesson_description %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :lesson_slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<div class="lessonContainer">
  <h1>Lessons</h1>
  <div class="lesson-table">
    <table>
      <tbody>
      <% @lessons.each do |lesson| %>
        <tr>
            <td><%= link_to lesson&.name, lesson %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div>

  <br>
</div>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<div class="fond" id="smoothscroll">	
  <div class="button-flip">	
  </div>	
</div>

<%= react_component(@lesson.name, props: { description: @lesson.description } , prerender: false) %>


<div class="footer-info" id="mark-complete">
  <% if @completed && (@completed.user_id == current_user.id) && @completed.completed == true%>
  <p><span class='lesson-complete'>Lesson Complete <%= l(@completed.created_at, format: :short) %> </span></p>
    <%= link_to 'mark incomplete', togglelesson_path(@completed), :method => :put %>

  <% elsif @completed && (@completed.user_id == current_user.id) && @completed.completed == false%>
   <%= link_to 'mark complete', togglelesson_path(@completed), :method => :put %>
  <% else %>
    <%= render :partial => 'completed_lessons/form' %>
  <% end %>
  <%= button_to 'Back', lessons_path, :method => "get", :class => "btn back-btn" %>
</div>

app/views/pages/info.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scimo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "/css/style.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'skrollr.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body id="skrollr-body">
    <section id="container" data-0="background-image:linear-gradient(90deg, hsl(172, 100%, 50%), hsl(318, 68%, 68%);" data-450="background-image:linear-gradient(450deg, hsl(172, 100%, 50%), hsl(318, 68%, 68%);">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#">All lessons</a>
                        </li>
                        <li>
                            <a href="#">Featured lessons</a>
                        </li>
                        <li>
                            <a href="#">Team</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                            <img class="img-responsive" src="images/gifs/faces-fast.gif" alt="">
                                        </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                            <img class="img-responsive" src="images/gifs/tube-2.png" alt="">
                                        </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                            <img class="img-responsive" src="images/gifs/tube.gif" alt="">
                                        </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                            <img class="img-responsive" src="images/gifs/faces-1.png" alt="">
                                        </a>
                </div>
            </div>
            <!-- /.row -->
            <div class="col-lg-12">
                <div class="header">
                    <h1>ScienceMotions</h1>
                    <p>Biology, chemistry and physics lessons from the future.</p>
                    <p><a style="color:white" href="#">see more</a></p>
                </div>
            </div>
            <!-- Projects Row -->
            <div class="row">
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/tube-bright.gif" alt="">
                                         </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/faces-3.png" alt="">
                                         </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/tube-1.png" alt="">
                                         </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/faces.gif" alt="">
                                         </a>
                </div>
            </div>
            <!-- /.row -->
            <!-- Projects Row -->
            <div class="row">
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/faces-2.png" alt="">
                                         </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/tube-bright.gif" alt="">
                                         </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/faces-1.png" alt="">
                                         </a>
                </div>
                <div class="col-md-3 portfolio-item">
                    <a href="#">
                                             <img class="img-responsive" src="images/gifs/tube.gif" alt="">
                                         </a>
                </div>
            </div>
        </div>
        <!-- /.container -->
        <!-- jQuery -->
    </section>
    <section id="second">
        <div class="container">
            <!-- /.row -->
            <div class="col-lg-12">
                <div class="header">
                    <br/>
                    <p><a href="#">See all lessons here</a></p>
                    <h1>Featured Lessons</h1>
                    <br/>
                </div>
            </div>
            <!-- Projects Row -->
            <div class="row">
                <div class="col-md-4 portfolio-item class">
                    <a href="#">
                        <h1>Atoms</h1>
                    </a>
                </div>
                <div class="col-md-4 portfolio-item dna">
                    <a href="#">
                        <h1>DNA</h1>
                    </a>
                </div>
                <div class="col-md-4 portfolio-item eye">
                    <a href="#">
                        <h1>Eye</h1>
                    </a>
                </div>

            </div>
            <!-- Projects Row -->
            <div class="row">
                <div class="col-md-4 portfolio-item sound">
                    <a href="#">
                        <h1>Sound waves</h1>
                    </a>
                </div>
                <div class="col-md-4 portfolio-item diffusion">
                    <a href="#">
                        <h1>Diffusion</h1>
                    </a>
                </div>
                <div class="col-md-4 portfolio-item class">
                    <a href="#">
                        <h1>Classification</h1>
                    </a>
                </div>

            </div>
            <div class="row">
                <br/>
            </div>
        </div>
    </section>
    <section id="test">
        <div class="container">
            <div class="col-lg-12">
                <div class="header">
                    <br/>
                    <h1>Testimonials</h1>
                    <br/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 portfolio-item class">
                    <p>
                        <i>“It looks really cool! I use GCSE Bitesize but it doesn’t always explain things that well.”</i></p>
                    <p> Blessing, GCSE Student, Brixton </p>
                </div>
                <div class="col-md-6 portfolio-item dna">
                    <p>
                        <i> “This looks like it would be very helpful. Right now I use Gojimo, but it just uses lots of questions”</i></p>
                    <p>Joseph, A-Level Biology Student, Camberwell
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End mc_embed_signup  -->
    <footer id="footer">
        <!-- Begin MailChimp Signup Form -->
        <!-- <link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css"> -->
        <div class="row">
            <div class="col-md-12 portfolio-item">
                <div id="mc_embed_signup">
                    <form action="//jhn.us16.list-manage.com/subscribe/post-json?u=70d8e0ea2d8800a5f4e06792c&amp;id=b5095bc718&c=?" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll">
                            <div>
                                <span style="color:#fff;"> <i><p>Science is about how shapes move in space, so we think animation is the best way to explain it... and we want to explain it in a way that's as fun to look at as MTV.</p></i></span>
                            </div>
                            <label for="mce-EMAIL">Subscribe to our mailing list!</label>
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div style="position: absolute; left: -5000px;" aria-hidden="true">
                                <input type="text" name="b_70d8e0ea2d8800a5f4e06792c_b5095bc718" tabindex="-1" value="">
                            </div>
                            <div class="clear">
                                <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
                            </div>
                        </div>
                        <div id="notification_container"></div>
                    </form>
                </div>
            </div>
        </div>
        <script src="js/jquery.js"></script>
        <script type="text/javascript">
        $(function() {
            var $form = $('#mc-embedded-subscribe-form');
            $('#mc-embedded-subscribe').on('click', function(event) {
                if (event) event.preventDefault();
                register($form);
            });
        });
        function register($form) {
            $.ajax({
                type: $form.attr('method'),
                url: $form.attr('action'),
                data: $form.serialize(),
                cache: false,
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                error: function(err) { $('#notification_container').html('<span class="alert">Could not connect to server. Please try again later.</span>'); },
                success: function(data) {
                    if (data.result != "success") {
                        var message = data.msg.substring();
                        $('#notification_container').html('<span class="alert">' + message + '</span>');
                    } else {
                        var message = data.msg;
                        $('#notification_container').html('<span class="success">' + message + '</span>');
                    }
                }
            });
        }
        </script>
        <!--End mc_embed_signup-->
        <!-- <ul class="actions">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
                <li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
                <li><a href="#" class="icon fa-pinterest"><span class="label">Pinterest</span></a></li>
                <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
            </ul> -->
    </footer>
    <!-- Bootstrap Core JavaScript -->
    <script src="/bootstrap.min.js"></script>
    <script type="text/javascript" src="/skrollr.min.js"></script>
    <script type="text/javascript" src="/scrollnav.js"></script>
    <script type="text/javascript">
    skrollr.init();
    </script>
</body>

app/views/team/index.html.erb
<%= react_component("Team", prerender: false) %>